name: "Webhook"
guid: "71552A5A-5C5C-4350-A2AE-EBE451A30173"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 12
targetAbi: "10.8.8.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Crypto.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |2-
  ### New features and improvements ###
  - Added MQTT as a destination (#134) @darickc
  - [Templates] Telegram & ntfy templates with special instructions (#130) @Fallenbagel

  ### Bug Fixes ###
  - Clear config when loading page (#115) @crobibero

  ### Code or Repo Maintenance ###
  - Update dependencies and fix stylecop (#138) @crobibero

  ### Documentation updates ###
  - Add handlebar templates for Pushover (#153) @manuel-rw

  ### Dependency updates ###
  - chore(deps): update dependency mqttnet.extensions.managedclient to v4.1.4.563 (#151) @renovate
  - chore(deps): update dependency mailkit to v3.4.3 (#149) @renovate
  - chore(deps): update dependency mqttnet.extensions.managedclient to v4.1.3.436 (#145) @renovate
  - chore(deps): update dependency mailkit to v3.4.2 (#142) @renovate
  - chore(deps): update dependency mqttnet.extensions.managedclient to v4.1.2.350 (#141) @renovate
  - chore(deps): update dependency mailkit to v3.4.1 (#135) @renovate
  - chore(deps): update dependency mailkit to v3.3.0 (#119) @renovate
  - chore(deps): bump Handlebars.Net from 2.1.0 to 2.1.2 (#111) @dependabot

  ### CI & build changes ###
  - fix: meta ci workflows (#116) @h1dden-da3m0n
